name: Publish to Chrome Web Store.

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'manifest.json'

jobs:
  Chrome:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


    - name: Pack extension

      uses: TheDoctor0/zip-release@0.4.1

      with:

        filename: ./Package.zip

        exclusions: '.git/* .vscode/* .github/* *.md'




    - name: Publish to Chrome Webstore

      uses: SebastienGllmt/chrome-addon@v3

      with:

        extension: jafgelpkkkopeaefadkdjcmnicgpcncc

        zip: ./Package.zip

        client-id: ${{ secrets.G_CLIENT_ID }}

        client-secret: ${{ secrets.G_CLIENT_SECRET }}

        refresh-token: ${{ secrets.G_REFRESH_TOKEN }}




    - name: Drop artifacts

      uses: actions/upload-artifact@v2

      with:

        name: 'Chrome Artifacts'

        path: ./Package.zip





